name: Primer Workflow (push)
on: [push]
jobs:
  build:
    name: Hola Mundo
    runs-on: ubuntu-latest
    steps:
      - id: firstStep
        name: Hola mundo
        uses: fmonper1/cice-action-pruba@master
        with:
          persona: 'Cice'
      - name: Imprima la hora actual
        run: echo 'La hora es ${{ steps.firstStep.outputs.hora }}'
